# Generated by Django 4.1.3 on 2022-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_team', models.CharField(max_length=30)),
                ('second_team', models.CharField(max_length=30)),
                ('match_date', models.DateTimeField()),
                ('score', models.CharField(max_length=5)),
            ],
        ),
    ]
