# Generated by Django 4.1.3 on 2022-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='score',
        ),
        migrations.AddField(
            model_name='scores',
            name='score_first_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scores',
            name='score_second_team',
            field=models.IntegerField(default=0),
        ),
    ]
