# Generated by Django 4.1.3 on 2022-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_remove_scores_score_scores_score_first_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='first_team_icon',
            field=models.URLField(default='null'),
        ),
        migrations.AddField(
            model_name='scores',
            name='second_team_icon',
            field=models.URLField(default='null'),
        ),
    ]
