# Generated by Django 4.1.3 on 2022-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_players_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='current_team',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
