# Generated by Django 4.1.3 on 2022-12-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_players_current_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='players',
            name='first_team_icon',
        ),
        migrations.RemoveField(
            model_name='players',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='players',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='players',
            name='score_first_team',
        ),
        migrations.RemoveField(
            model_name='players',
            name='score_second_team',
        ),
        migrations.RemoveField(
            model_name='players',
            name='second_team',
        ),
        migrations.RemoveField(
            model_name='players',
            name='second_team_icon',
        ),
    ]
