# Generated by Django 4.1.3 on 2022-12-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_remove_players_first_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('first_team', models.CharField(max_length=30)),
                ('first_team_icon', models.URLField(default='null')),
                ('second_team', models.CharField(max_length=30)),
                ('second_team_icon', models.URLField(default='null')),
                ('match_date', models.DateTimeField()),
                ('score_first_team', models.IntegerField(default=0)),
                ('score_second_team', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.players')),
            ],
        ),
    ]
