# Generated by Django 4.1.3 on 2023-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_player_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='photo',
            field=models.ImageField(default='url', upload_to='photos/players/'),
        ),
    ]
