# Generated by Django 4.1.3 on 2023-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_players_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champions_League_Scores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_team', models.CharField(max_length=30)),
                ('first_team_icon', models.URLField(default='null')),
                ('second_team', models.CharField(max_length=30)),
                ('second_team_icon', models.URLField(default='null')),
                ('match_date', models.DateTimeField()),
                ('score_first_team', models.IntegerField(default=0)),
                ('score_second_team', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Матч ЛЧ',
                'verbose_name_plural': 'Все матчи ЛЧ',
                'ordering': ['-match_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='player_matches',
            options={'ordering': ['player'], 'verbose_name': 'Матч игрока', 'verbose_name_plural': 'Матчи игроков'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'ordering': ['-match_date'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Все матчи'},
        ),
    ]
